"""Add certificate_file column to Certificate

Revision ID: 9768b44cea52
Revises: 21f483860e7a
Create Date: 2025-12-07 10:59:00.866729

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9768b44cea52'
down_revision = '21f483860e7a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('certificates', schema=None) as batch_op:
        batch_op.alter_column('certificate_file',
               existing_type=sa.TEXT(),
               type_=sa.String(length=200),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('certificates', schema=None) as batch_op:
        batch_op.alter_column('certificate_file',
               existing_type=sa.String(length=200),
               type_=sa.TEXT(),
               existing_nullable=True)

    # ### end Alembic commands ###
