"""Add address to Institution

Revision ID: e39e5eeb6cf6
Revises: 9768b44cea52
Create Date: 2025-12-07 11:08:24.382458

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e39e5eeb6cf6'
down_revision = '9768b44cea52'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('institutions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('address', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('institutions', schema=None) as batch_op:
        batch_op.drop_column('address')

    # ### end Alembic commands ###
